# Generated by Django 2.1.3 on 2018-12-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedroom',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='sqrt',
            new_name='sqft',
        ),
    ]
